# Generated by Django 5.0.4 on 2024-05-10 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appJeni', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mascota',
            name='animal',
        ),
        migrations.RemoveField(
            model_name='raza',
            name='animal',
        ),
        migrations.RemoveField(
            model_name='historialcita',
            name='cita',
        ),
        migrations.RemoveField(
            model_name='historialcita',
            name='mascota',
        ),
        migrations.RemoveField(
            model_name='mascota',
            name='raza',
        ),
        migrations.RemoveField(
            model_name='vacunacion',
            name='mascota',
        ),
        migrations.RemoveField(
            model_name='vacunacion',
            name='tipo_vacuna',
        ),
        migrations.DeleteModel(
            name='AnimalMascota',
        ),
        migrations.DeleteModel(
            name='Cita',
        ),
        migrations.DeleteModel(
            name='HistorialCita',
        ),
        migrations.DeleteModel(
            name='Raza',
        ),
        migrations.DeleteModel(
            name='Mascota',
        ),
        migrations.DeleteModel(
            name='Vacuna',
        ),
        migrations.DeleteModel(
            name='Vacunacion',
        ),
    ]
